server:
  port: 8080

spring:
  application:
    name: aggregator-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/aggregator}
    username: ${DATABASE_USER:aggregator}
    password: ${DATABASE_PASSWORD:aggregatorpassword}
  jackson:
    serialization:
      write-empty-json-arrays: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

aggregation:
  tools:
    java:
      pmd: ${PMD_URL:http://localhost:8090}
      checkstyle: ${CHECKSTYLE_URL:http://localhost:8092}
      infer: ${INFER_URL:http://localhost:8093}
    javascript:
      pmd: ${PMD_URL:http://localhost:8090}
      eslint: ${ESLINT_URL:http://localhost:8091}
    c:
      infer: ${INFER_URL:http://localhost:8093}
      cppcheck: ${CPPCHECK_URL:http://localhost:8094}
  exchange:
    maximum-timeout: 10

