server:
  port: 8080

spring:
  application:
    name: aggregator-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/aggregator}
    username: ${DATABASE_USER:aggregator}
    password: ${DATABASE_PASSWORD:aggregatorpassword}
  jackson:
    serialization:
      write-empty-json-arrays: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    contexts: ${spring.profiles.active}

aggregation:
  exchange:
    maximum-timeout: 10
